added minDate, maxDate
vk-lab/react-month-picker-input pull request #38
Opened 2019-10-04 15:31 UTC by UACephei

2019-10-04 16:23 UTC, slavakisel requested changes
Also update README.md

2019-10-04 16:23 UTC, slavakisel commented on docs/index.tsx
> +      <h2>With limits minDate and maxDate</h2>
"Limit selection with minDate or maxDate constraints"

2019-10-07 21:05 UTC, widua33 requested changes

2019-10-07 21:05 UTC, widua33 commented on src/utils.ts
> +  minDateValid[1] > maxDateValid[1] ? minDateValid = [1, 1] : minDateValid[1];
Если `minDate` будет к примеру `[10, 2015]`, a `maxDate` = `[09, 2015]`, правильно ли будет работать 
этот код?

2019-10-07 21:05 UTC, Widua commented on src/calendar/MonthCalendar.tsx
> +    const [maxDateMonth, maxDateYear] = this.minMaxDate()[1];
Попробуй так сделать `const [[minDateMonth, minDateYear], [maxDateMonth, maxDateYear]] = this.minMaxDate();`

2019-10-07 21:05 UTC, Widua commented on src/calendar/MonthCalendar.tsx
> +      selectedMonth = selectedMonth > maxDateMonth -1 ? maxDateMonth -1 : selectedMonth;
Лучше так не писать `-1`, не очень читаемо. Так намного лучше `selectedMonth > maxDateMonth - 1`

2019-10-07 21:05 UTC, Widua commented on src/utils.ts
> +  const month = monthNum-1;
Ну и тут тоже лучше пробелы оставлять

2019-10-07 21:05 UTC, Widua commented on src/utils.ts
> +    } else if (maxDate && maxDate.length!=2){
Ну и в условиях

2019-10-08 06:51 UTC, UACephei commented on src/utils.ts
> +  minDateValid[1] > maxDateValid[1] ? minDateValid = [1, 1] : minDateValid[1];
да

2019-10-08 06:52 UTC, UACephei commented on src/calendar/MonthCalendar.tsx
> +      selectedMonth = selectedMonth > maxDateMonth -1 ? maxDateMonth -1 : selectedMonth;
ок

2019-10-08 07:19 UTC, Widua commented on src/utils.ts
> +  minDateValid[1] > maxDateValid[1] ? minDateValid = [1, 1] : minDateValid[1];
Оставь раз написал уже, будет понятное сообщение об ошибке

2019-10-08 07:28 UTC, widua33 requested changes

2019-10-08 07:28 UTC, Widua commented on src/utils.ts
> +    } else if (maxDate && maxDate.length !=2 ){
Неправильно пробел поставил

2019-10-08 07:28 UTC, Widua commented on src/utils.ts
> +  } else if (maxDate && maxDate.length!=2){
Тут тоже надо пробелы добавить

2019-10-08 07:48 UTC, widua33 approved these changes

2019-10-08 11:54 UTC, slavakisel approved these changes

2019-10-08 11:54 UTC, merged

2019-10-08 12:00 UTC, slavakisel commented
resolves #12